/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#f8fafc',
          500: '#111827',
          700: '#0f172a',
        },
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#8f4c2f",
        "inverse-surface": "#31302f",
        "tertiary": "#605b56",
        "tertiary-container": "#79746e",
        "secondary-container": "#e9ddd7",
        "surface-bright": "#fcf9f6",
        "on-tertiary-fixed-variant": "#4a4641",
        "on-secondary-fixed-variant": "#4d4541",
        "inverse-on-surface": "#f3f0ed",
        "surface": "#fcf9f6",
        "on-error": "#ffffff",
        "surface-container-low": "#f6f3f0",
        "on-tertiary": "#ffffff",
        "on-background": "#1c1c1a",
        "primary-fixed-dim": "#ffb597",
        "surface-container-high": "#eae8e5",
        "secondary": "#655d58",
        "ink-light": "#5A4E48",
        "outline": "#86736c",
        "on-surface-variant": "#53433d",
        "outline-variant": "#d9c2b9",
        "clay-dark": "#A85E40",
        "surface-dim": "#dcdad7",
        "secondary-fixed-dim": "#cfc4be",
        "on-primary-fixed-variant": "#72351a",
        "surface-container": "#f0edea",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#360f00",
        "primary-fixed": "#ffdbcd",
        "cream-warm": "#F2ECE6",
        "sage": "#D6E4D8",
        "tertiary-fixed": "#e9e1da",
        "primary": "#8c4a2d",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#201a17",
        "on-tertiary-fixed": "#1e1b17",
        "background": "#fcf9f6",
        "surface-variant": "#e5e2df",
        "on-secondary-container": "#69615c",
        "inverse-primary": "#ffb597",
        "on-surface": "#1c1c1a",
        "border-subtle": "#E8DDD6",
        "primary-container": "#aa6243",
        "surface-container-highest": "#e5e2df",
        "tertiary-fixed-dim": "#ccc5bf",
        "on-tertiary-container": "#fffbff",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-primary-container": "#fffbff",
        "secondary-fixed": "#ece0da",
        // Admin dashboard colors from HTML
        "on-error": "#ffffff",
        "surface-container-high": "#e9e8e9",
        "on-tertiary-fixed": "#211b00",
        "surface-dim": "#dbdadb",
        primary: "#094cb2",
        "tertiary-fixed-dim": "#dcc661",
        "secondary-fixed": "#dfe3e8",
        "secondary-fixed-dim": "#c2c7cc",
        "surface-tint": "#2259bf",
        "on-primary-container": "#e7ebff",
        "tertiary-container": "#bfab49",
        "error-container": "#ffdad6",
        outline: "#737784",
        "inverse-on-surface": "#f2f0f1",
        "inverse-primary": "#b1c5ff",
        "primary-fixed-dim": "#b1c5ff",
        "on-secondary-fixed-variant": "#42474b",
        "surface-bright": "#faf9fa",
        "surface-container-low": "#f5f3f4",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c3c6d5",
        "on-primary-fixed": "#001946",
        "on-tertiary-container": "#4a3f00",
        "on-surface": "#1b1c1d",
        "on-primary": "#ffffff",
        "surface-container": "#efedee",
        "secondary-container": "#dfe3e8",
        "on-tertiary-fixed-variant": "#524600",
        "surface-variant": "#e3e2e3",
        tertiary: "#6d5e00",
        "on-error-container": "#93000a",
        "primary-container": "#3366cc",
        "on-secondary-container": "#606569",
        secondary: "#5a5f63",
        "on-tertiary": "#ffffff",
        background: "#faf9fa",
        "on-secondary-fixed": "#171c20",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#434653",
        "surface-container-highest": "#e3e2e3",
        "primary-fixed": "#d9e2ff",
        "inverse-surface": "#303031",
        "tertiary-fixed": "#f9e37a",
        "on-primary-fixed-variant": "#00419d",
        surface: "#faf9fa",
        error: "#ba1a1a",
        "on-background": "#1b1c1d"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "grid-gutter": "24px",
        "element-gap-lg": "32px",
        "container-max": "1440px",
        "section-gap-mobile": "48px",
        "section-gap-desktop": "80px",
        "element-gap-sm": "8px",
        "element-gap-md": "16px",
        // Admin dashboard spacing from HTML
        "row_height": "56px",
        "card_gap": "24px",
        "base_unit": "8px",
        "sidebar_width": "260px",
        "container_padding": "32px"
      },
      fontFamily: {
        "display-mobile": ["DM Serif Display"],
        "body-lg": ["DM Sans"],
        "body-md": ["DM Sans"],
        "headline-md": ["DM Serif Display"],
        "caption": ["DM Sans"],
        "label-uppercase": ["DM Sans"],
        "headline-lg": ["DM Serif Display"],
        "display": ["DM Serif Display"],
        // Admin dashboard fonts from HTML
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "headline-md": ["DM Sans"],
        "display-lg-mobile": ["DM Sans"],
        "data-tabular": ["Inter"],
        "display-lg": ["DM Sans"],
        "label-caps": ["Inter"],
        "title-sm": ["Inter"],
        headline: ["Noto Serif"],
        display: ["Noto Serif"],
        body: ["Inter"],
        label: ["Public Sans"]
      },
      fontSize: {
        "display-mobile": ["44px", { "lineHeight": "1.2", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "1.8", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "1.85", "fontWeight": "400" }],
        "headline-md": ["32px", { "lineHeight": "1.3", "fontWeight": "400" }],
        "caption": ["11px", { "lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "label-uppercase": ["12px", { "lineHeight": "1.2", "letterSpacing": "0.15em", "fontWeight": "500" }],
        "headline-lg": ["40px", { "lineHeight": "1.3", "fontWeight": "400" }],
        "display": ["80px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        // Admin dashboard font sizes from HTML
        "body-md": ["14px", {lineHeight: "20px", fontWeight: "400"}],
        "body-sm": ["13px", {lineHeight: "18px", fontWeight: "400"}],
        "headline-md": ["24px", {lineHeight: "32px", fontWeight: "600"}],
        "display-lg-mobile": ["28px", {lineHeight: "36px", fontWeight: "700"}],
        "data-tabular": ["14px", {lineHeight: "20px", fontWeight: "500"}],
        "display-lg": ["36px", {lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700"}],
        "label-caps": ["11px", {lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700"}],
        "title-sm": ["18px", {lineHeight: "24px", fontWeight: "600"}]
      }
    },
  },
  plugins: [],
};

