/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#f8fafc',
          500: '#111827',
          700: '#0f172a',
        },
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#8f4c2f",
        "inverse-surface": "#31302f",
        "tertiary": "#605b56",
        "tertiary-container": "#79746e",
        "secondary-container": "#e9ddd7",
        "surface-bright": "#fcf9f6",
        "on-tertiary-fixed-variant": "#4a4641",
        "on-secondary-fixed-variant": "#4d4541",
        "inverse-on-surface": "#f3f0ed",
        "surface": "#fcf9f6",
        "on-error": "#ffffff",
        "surface-container-low": "#f6f3f0",
        "on-tertiary": "#ffffff",
        "on-background": "#1c1c1a",
        "primary-fixed-dim": "#ffb597",
        "surface-container-high": "#eae8e5",
        "secondary": "#655d58",
        "ink-light": "#5A4E48",
        "outline": "#86736c",
        "on-surface-variant": "#53433d",
        "outline-variant": "#d9c2b9",
        "clay-dark": "#A85E40",
        "surface-dim": "#dcdad7",
        "secondary-fixed-dim": "#cfc4be",
        "on-primary-fixed-variant": "#72351a",
        "surface-container": "#f0edea",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#360f00",
        "primary-fixed": "#ffdbcd",
        "cream-warm": "#F2ECE6",
        "sage": "#D6E4D8",
        "tertiary-fixed": "#e9e1da",
        "primary": "#8c4a2d",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#201a17",
        "on-tertiary-fixed": "#1e1b17",
        "background": "#fcf9f6",
        "surface-variant": "#e5e2df",
        "on-secondary-container": "#69615c",
        "inverse-primary": "#ffb597",
        "on-surface": "#1c1c1a",
        "border-subtle": "#E8DDD6",
        "primary-container": "#aa6243",
        "surface-container-highest": "#e5e2df",
        "tertiary-fixed-dim": "#ccc5bf",
        "on-tertiary-container": "#fffbff",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-primary-container": "#fffbff",
        "secondary-fixed": "#ece0da"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "grid-gutter": "24px",
        "element-gap-lg": "32px",
        "container-max": "1440px",
        "section-gap-mobile": "48px",
        "section-gap-desktop": "80px",
        "element-gap-sm": "8px",
        "element-gap-md": "16px"
      },
      fontFamily: {
        "display-mobile": ["DM Serif Display"],
        "body-lg": ["DM Sans"],
        "body-md": ["DM Sans"],
        "headline-md": ["DM Serif Display"],
        "caption": ["DM Sans"],
        "label-uppercase": ["DM Sans"],
        "headline-lg": ["DM Serif Display"],
        "display": ["DM Serif Display"]
      },
      fontSize: {
        "display-mobile": ["44px", { "lineHeight": "1.2", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "1.8", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "1.85", "fontWeight": "400" }],
        "headline-md": ["32px", { "lineHeight": "1.3", "fontWeight": "400" }],
        "caption": ["11px", { "lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "label-uppercase": ["12px", { "lineHeight": "1.2", "letterSpacing": "0.15em", "fontWeight": "500" }],
        "headline-lg": ["40px", { "lineHeight": "1.3", "fontWeight": "400" }],
        "display": ["80px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
};

