/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        'primary-soft': 'var(--color-primary-soft)',
        'primary-container': 'var(--color-primary-container)',
        'on-primary': 'var(--color-on-primary)',
        'on-primary-container': 'var(--color-on-primary-container)',
        secondary: 'var(--color-secondary)',
        'secondary-soft': 'var(--color-secondary-soft)',
        accent: 'var(--color-accent)',
        tertiary: 'var(--color-tertiary)',
        background: 'var(--color-bg-base)',
        surface: 'var(--color-bg-card)',
        'surface-container-low': 'var(--color-bg-muted)',
        'surface-container': 'var(--color-bg-soft)',
        'surface-container-high': 'var(--color-bg-soft-strong)',
        'surface-container-highest': 'var(--color-bg-soft-strong)',
        'surface-container-lowest': 'var(--color-bg-card)',
        'surface-bright': 'var(--color-bg-card)',
        'border-subtle': 'var(--color-border)',
        'ink-light': 'var(--color-text-secondary)',
        'on-surface': 'var(--color-text-primary)',
        'on-surface-variant': 'var(--color-text-secondary)',
        'clay-dark': 'var(--color-primary)',
        'cream-warm': 'var(--color-accent-soft)',
        sage: 'var(--color-mint)',
        error: 'var(--color-error)',
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
        info: 'var(--color-info)',
        outline: 'var(--color-border)',
        'outline-variant': 'var(--color-border)',
      },
      borderRadius: {
        none: '0px',
        sm: '10px',
        DEFAULT: '16px',
        md: '18px',
        lg: '22px',
        xl: '28px',
        '2xl': '32px',
        '3xl': '40px',
        full: '9999px',
      },
      spacing: {
        'grid-gutter': '24px',
        'element-gap-lg': '32px',
        'container-max': '1440px',
        'section-gap-mobile': '48px',
        'section-gap-desktop': '80px',
        'element-gap-sm': '8px',
        'element-gap-md': '16px',
      },
      fontFamily: {
        sans: ['Nunito', 'Quicksand', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        display: ['Quicksand', 'Nunito', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'display-mobile': ['Quicksand', 'Nunito', 'sans-serif'],
        'display-lg': ['Quicksand', 'Nunito', 'sans-serif'],
        'body-lg': ['Nunito', 'Quicksand', 'sans-serif'],
        'body-md': ['Nunito', 'Quicksand', 'sans-serif'],
        'body-sm': ['Nunito', 'Quicksand', 'sans-serif'],
        'headline-md': ['Quicksand', 'Nunito', 'sans-serif'],
        'headline-lg': ['Quicksand', 'Nunito', 'sans-serif'],
        caption: ['Nunito', 'Quicksand', 'sans-serif'],
        'label-uppercase': ['Nunito', 'Quicksand', 'sans-serif'],
        'label-caps': ['Nunito', 'Quicksand', 'sans-serif'],
        headline: ['Quicksand', 'Nunito', 'sans-serif'],
        body: ['Nunito', 'Quicksand', 'sans-serif'],
        label: ['Nunito', 'Quicksand', 'sans-serif'],
        'data-tabular': ['Nunito', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-mobile': ['48px', { lineHeight: '1.12', letterSpacing: '0', fontWeight: '800' }],
        display: ['64px', { lineHeight: '1.05', letterSpacing: '0', fontWeight: '800' }],
        'display-lg': ['56px', { lineHeight: '1.08', letterSpacing: '0', fontWeight: '800' }],
        'headline-lg': ['40px', { lineHeight: '1.16', letterSpacing: '0', fontWeight: '800' }],
        'headline-md': ['32px', { lineHeight: '1.2', letterSpacing: '0', fontWeight: '800' }],
        'title-sm': ['20px', { lineHeight: '1.35', letterSpacing: '0', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.65', letterSpacing: '0', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.65', letterSpacing: '0', fontWeight: '500' }],
        'body-sm': ['14px', { lineHeight: '1.55', letterSpacing: '0', fontWeight: '500' }],
        caption: ['12px', { lineHeight: '1.45', letterSpacing: '0', fontWeight: '700' }],
        'label-uppercase': ['13px', { lineHeight: '1.2', letterSpacing: '0', fontWeight: '800' }],
        'label-caps': ['12px', { lineHeight: '1.2', letterSpacing: '0', fontWeight: '800' }],
      },
      boxShadow: {
        premium: '0 18px 45px -24px rgba(96, 165, 250, 0.45)',
        soft: '0 14px 35px -18px rgba(96, 165, 250, 0.35)',
        card: '0 20px 50px -28px rgba(51, 65, 85, 0.25)',
        button: '0 12px 24px -14px rgba(96, 165, 250, 0.75)',
      },
    },
  },
  plugins: [],
};
